### ISSUE TITLE
EM TODAS AS FICHAS TÉCNICAS !!!

### ISSUE THREAD

**Issue by rgualdanineto** [filipecoelho/sig-intermultiplas#110]
EM TODAS AS FICHAS TÉCNICAS !!! - Deve ser colocado um campo OBSERVAÇÕES, onde o Lupércio informará posteriormente o que deverá ser escrito.

**Comment by filipecoelho** [comment]
Hoje já existe um campo de observações que é extraído do relatório mensal, que o próprio Lupércio preenche, deve-se criar outro campo?
As observações do relatório mensal aparece nas fichas em "Situação da Obra"
