### ISSUE TITLE
Erro com download de fotos do RDO

### ISSUE THREAD

**Issue by danieldepaula** [filipecoelho/sig-intermultiplas#118]
"No such file exists."

**Comment by filipecoelho** [comment]
@danieldepaula efetuei a correção, porém pode ocorrer novamente e quando houver, preciso das seguintes informações:
- Empreendimento
- Local (ex.: Ficha Técnica da Obra, Acompanhamento de Obra, Registro de RDO, etc)
- Nome do arquivo
