### ISSUE TITLE
Controle de acesso nos registros de Acompanhamento de Obras

### ISSUE THREAD

**Issue by claudineysiqueira** [filipecoelho/sig-intermultiplas#121]
O Engenheiro e o Fiscal do Consórcio (ambos obras) só poderão acessar empreendimentos que estão participando para elaboração dos RDO's.
Para isso já foi alimentado no sistema (tb_pi) nos campos "eng_obras_consorcio" e "fiscal_consorcio" as pessoas autorizadas para cada empreendimento.
Você comentou que mudaria a estrutura (lay-out) da tabela de acessos, porém os colaboradores serão estes.

**Comment by filipecoelho** [comment]
Procedimentos p/ implantação:
- Importar planilha amarração cod_fiscal (tabela tb_responsavel) x cod_usuario (tabela login)
- Criar consulta de atualização p/ atualizar campo cod_usuario (tabela tb_responsavel)
