### ISSUE TITLE
desenvolver relatório de atividades no sistema

### ISSUE THREAD

**Issue by rgualdanineto** [filipecoelho/sig-intermultiplas#16]
este relatório é muito importante para o gestor perceber as mudanças diárias no sistema.

**Comment by filipecoelho** [comment]
Etapas para implantar o chamado:
- Criar coluna cod_situacao_atual_obra (Número) na tabela tb_acompanhamento
- Copiar o valor da coluna cod_situacao da tabela tb_pi para a coluna criada acima
- Replicar a consulta c_lista_rel_ultimas_ocorrencias
