### ISSUE TITLE
Previsão Inauguração

### ISSUE THREAD

**Issue by lisianelaier** [filipecoelho/sig-intermultiplas#169]
Relatório: Resumo da situação por município e municipalidade
Coluna "Previsão Inauguração" -> formato: texto

**Comment by filipecoelho** [comment]
O campo já está com o formato de texto, entretanto, na tela de alteração de dados do empreendimento, onde se alimenta o campo, somente era possível informar uma data.

Procedimento p/ implantação:
- Atualizar página altera_pi.asp

**Comment by lisianelaier** [comment]
As datas precisam aparecer no formato MMM/AA no relatório do Lupércio.  Esta solicitação é dele....
