### ISSUE TITLE
MEIO AMBIENTE

### ISSUE THREAD

**Issue by claudineysiqueira** [filipecoelho/sig-intermultiplas#173]
De: Claudiney Siqueira [mailto:claudiney.siqueira@intermultiplas.com.br] 
Enviada em: segunda-feira, 25 de maio de 2015 17:32
Para: Filipe Coelho <filipe.mendonca.coelho@gmail.com> (filipe.mendonca.coelho@gmail.com); amanda@intermultiplas.com.br
Cc: Rinaldo <rinaldo.neto@intermultiplas.com.br> (rinaldo.neto@intermultiplas.com.br)
Assunto: MEIO AMBIENTE

**Comment by filipecoelho** [comment]
Procedimento p/ implantação:
- Criar tabela tb_situacao_documento com os campos:
  - id
  - dsc_situacao_documento
- Criar campo cod_situacao_documento na tabela tb_licenca_ambiental
- Atualizar consulta c_lista_licencas_ambientais
- Atualizar as páginas:
  - cad_licenca.asp
  - altera_licenca.asp
  - delete_licenca.asp
