### ISSUE TITLE
Subir via atualização - Informações da Fabiana.

### ISSUE THREAD

**Issue by claudineysiqueira** [filipecoelho/sig-intermultiplas#179]
Ver instruções do e-mail abaixo:

De: Claudiney Siqueira [mailto:claudiney.siqueira@intermultiplas.com.br] 
Enviada em: sexta-feira, 29 de maio de 2015 17:54
Para: Filipe Coelho <filipe.mendonca.coelho@gmail.com> (filipe.mendonca.coelho@gmail.com)
Cc: Lisiane Laier <lisiane@intermultiplas.com.br> (lisiane@intermultiplas.com.br); Rinaldo <rinaldo.neto@intermultiplas.com.br> (rinaldo.neto@intermultiplas.com.br)
Assunto: Backlog n° 179 - Subir via atualização - Informações da Fabiana.

**Comment by filipecoelho** [comment]
Será atendido pelo chamado #175
