### ISSUE TITLE
urgente corrigir tela de ficha técnica de obra programada para atendimento

### ISSUE THREAD

**Issue by rgualdanineto** [filipecoelho/sig-intermultiplas#18]
veja em prefeitura de areias
![image](https://cloud.githubusercontent.com/assets/11915509/7116089/f5652fd4-e1c4-11e4-9e91-1ecc2be76f34.png)

**Comment by filipecoelho** [comment]
O problema era ocasionado por conta do tamanho do iframe da tela inicial.
Corrigido através do chamado #24
