### ISSUE TITLE
Como faço para cancelar um aditamento de contrato?

### ISSUE THREAD

**Issue by lisianelaier** [filipecoelho/sig-intermultiplas#184]

**Comment by filipecoelho** [comment]
Para contratos com cronograma, o aditamento é baseado no cálculo e na fórmula repassados pela Karla, leva em consideração a comparação com o penúltimo cronograma e o último cronograma. Não é um valor digitável.
Nos casos onde não há cronograma e os valores de contrato são digitados manualmente, existe uma coluna nas telas de cadastro e alteração, chamado [Valor Total dos Aditivos].
