### ISSUE TITLE
Erro de upload de arquivo de Meio Ambiente

### ISSUE THREAD

**Issue by claudineysiqueira** [filipecoelho/sig-intermultiplas#186]
Para upload exibe uma mensagem de erro, porém quando Amanda consulta, o arquivo está lá.

**Comment by filipecoelho** [comment]
Claudiney, vamos tentar validar este erro juntos, pois não consegui replicá-lo, mesmo em produção.

**Comment by claudineysiqueira** [comment]
A Amanda anexou o erro para análise:

De: Amanda Ribeiro Rosa [mailto:amanda@intermultiplas.com.br] 
Enviada em: quarta-feira, 10 de junho de 2015 14:51
Para: 'Claudiney Siqueira'
Cc: filipe.mendonca.coelho@gmail.com
Assunto: RES: [sig-intermultiplas] Erro de upload de arquivo de Meio Ambiente (#186)

**Comment by filipecoelho** [comment]
Claudiney, quando o erro ocorrer novamente, vou precisar das seguintes informações:
- Município e 
- Localidade
