### ISSUE TITLE
Implementar tecla "Voltar" para Meio Ambiente

### ISSUE THREAD

**Issue by claudineysiqueira** [filipecoelho/sig-intermultiplas#188]
Implementar tecla "Voltar"; e
Opção de excluir arquivo, pois a Amanda incluiu um arquivo por engano, e precisou excluir todo registro e refazê-lo para corrigir.

**Comment by filipecoelho** [comment]
Botão voltar = Devido a modelagem da estrutura do sistema não é possível implementar um botão voltar. Com o redesenho do layout será implementado um novo menu de navegação, mais amigável.
Botão excluir anexo = já implementado.
