### ISSUE TITLE
Correções a serem feitas referente as Obras Concluídas

### ISSUE THREAD

**Issue by danieldepaula** [filipecoelho/sig-intermultiplas#198]
Corrigir conforme o e-mail abaixo:

De: Daniel de Paula [mailto:daniel.paula@intermultiplas.com.br] 
Enviada em: quarta-feira, 10 de junho de 2015 17:05
Para: 'filipe.mendonca.coelho@gmail.com'
Cc: rinaldo.neto@intermultiplas.com.br
Assunto: Backlog n° 198 - Correções a serem feitas referente as Obras Concluídas

**Comment by filipecoelho** [comment]
Procedimento p/ implantação:
- Atualizar página dashboard-obra-concluida.asp
- Atualizar página rel_obras_concluidas.asp
- Atualizar o arquivo js/loadMapaObra.js
- Atualizar as tabelas:
  - tb_info_emp_concluidos
  - tb_info_emp_concluidos_arquivo
