### ISSUE TITLE
FICHA COM PROBLEMA

### ISSUE THREAD

**Issue by lisianelaier** [filipecoelho/sig-intermultiplas#200]
Na ficha das obras "Programadas para atendimento", o link do nome do Prefeito não está funcionando corretamente.

**Comment by filipecoelho** [comment]
Lisiane, pode enviar um caso para que eu possa simular o problema?

**Comment by lisianelaier** [comment]
Ficha de Monte Azul Pta. - Sede

**Comment by lisianelaier** [comment]
(O nome do Prefeito de Monte Azul Pta. é Paulo Sérgio David. Está aparecendo: DANIELA DE CÁSSIA SANTOS).

**Comment by filipecoelho** [comment]
Lisiane, ao verificar no banco e também no sistema, o município de Monte Azul Paulista está cadastrado como prefeito a própria Daniela de Cássia Santos.
Neste caso, é possível fazer a alteração através da atualização do registro no próprio sistema.

**Comment by lisianelaier** [comment]
Hoje de manhã, verifiquei com o Daniel. O cadastro estava de interessados estava correto...

**Comment by lisianelaier** [comment]
Abri um novo chamado para a geração do relatório no cadastro dos municípios para podermos checar todos.
