### ISSUE TITLE
FICHAS "NÃO ATENDIDAS"

### ISSUE THREAD

**Issue by lisianelaier** [filipecoelho/sig-intermultiplas#203]
Não está carregando as diversas pendências:
-> Pendências de Licenciamento;
-> Pendências de Documentação Fundiária;
-> Pendências de Projetos Executivos;
-> Pendências de Programação de Recursos Financeiros
Vide ficha de Altinópolis.

**Comment by filipecoelho** [comment]
Lisiane, ao verificar no banco de dados e também no sistema, pude constatar que as pendências citadas não estão marcadas como válidas.

As pendências de [LICENCIAMENTO, PROJETO, RECURSOS FINANCEIROS e DOC. FUNDIARIA] somente irão aparecer quando alguém marcar como uma pendência válida.

No momento da definição desta funcionalidade foi levantado o ponto de que as pendências deveriam passar pelo seu crivo para que possam ser exibidas nas fichas.
Para marcar as pendências é necessário acessar a tela de acompanhamento de obra, verificar os registros de pendência, clicar em editar.

Na edição do registro de pendência existe um campo de checkbox para selecionar se aquela é uma pendência válida.

**Comment by lisianelaier** [comment]
Vc. tem como validar todas as pendências? É mais fácil deletar uma ou outra que estejam erradas do que entrar uma por uma para validá-las...
