### ISSUE TITLE
Ficha técnica - "atendido"

### ISSUE THREAD

**Issue by lisianelaier** [filipecoelho/sig-intermultiplas#206]
Não estáfuncionando o link do campo "Observações Gerais".

**Comment by filipecoelho** [comment]
Lisiane, ao testar no sistema, o campo está trazendo o valor digitado no campo Observações Gerais, no cadastro do empreendimento.
Para visualizar o campo entre com perfil de Info. Gerenciais, acesse a tela de Cadastro de Empreendimentos >> altere o cadastro de um empreendimento qualquer, o campo está localizado no final do formulário de alteração.

**Comment by filipecoelho** [comment]
O campo desejado é Últimas Informações.
Este campo era visível apenas ao perfil [SUPERINTENDENTE].
