### ISSUE TITLE
Fotos duplicadas das Obras Concluídas

### ISSUE THREAD

**Issue by danieldepaula** [filipecoelho/sig-intermultiplas#208]
Filipe, segue a lista das obras que ficaram com as fotos duplicadas nas fichas.
- Bady Bassitt
- Bálsamo
- Bariri
- Bilac
- Brodowski
- Buritama
- Cabrália Paulista
- Orlândia
- Paraíso
- Patrocínio Paulista
- Santa Lúcia
- Tambaú
- Tapiratiba
- Tejupá

**Comment by filipecoelho** [comment]
Procedimento p/ implantação:
- Atualizar tabela tb_info_emp_concluidos_arquivo
