### ISSUE TITLE
Exportar relatórios para Excel

### ISSUE THREAD

**Issue by claudineysiqueira** [filipecoelho/sig-intermultiplas#217]
A Lisiane comentou que quando ela exporta um relatório do sistema para extensão "xls", algumas vezes para realizar um segunda importação na sequência, o sistema não permite, assim sendo necessário fazer logout, e em seguida realizar um novo acesso.

**Comment by filipecoelho** [comment]
Claudiney, embora eu tenha conseguido replicar o problema, não consegui encontrar uma solução.
Vou trabalhar em outras alternativas de exportação para Excel e publicarei em breve.
