### ISSUE TITLE
PENDÊNCIA

### ISSUE THREAD

**Issue by claudineysiqueira** [filipecoelho/sig-intermultiplas#223]
No registro de "Pendências", ao habilitar a opção "Pendência concluída", em seguida informar "Data Resolução da Pendência" e "Ação Realizada", ao salvar aparentemente não altera o registro modificando o status, como por exemplo ver o link abaixo que, não saiu da opção de Pendências.

cod_acompanhamento: 4186
PI: 175
Data do Registro: 21/05/2015

http://www.programaagualimpa.net/altera_acomp.asp?cod_acompanhamento=4186

**Comment by filipecoelho** [comment]
Procedimento p/ implantação:
- atualizar páginas:
  - acompanhamento_inclui_admin.asp
  - altera_acomp.asp
