### ISSUE TITLE
Migrar campos e informações do cadastro de empreendimento para o cadastro de contrato

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/sig-intermultiplas#234]
Os dados constantes no cadastro de empreendimento são, na verdade, dados do contrato, portanto, os campos e as informações contidas neles, devem estar no cadastro de contrato.

**Comment by lisianelaier** [comment]
População Urbana - IBGE (2010) (hab);
Projeção de População (2030);
Investimento Governo SP;
Início das Obras;
% Executado;
Previsão de Término;
Concluída/Inaugurada em;
Previsão de Inauguração;	
Carga Orgânica Retirada (ton./mês);
Selecione o Eng. Obras Consórcio;
Selecione o Eng. DAEE;
Selecione o Eng. Plan. Obras Consórcio;
Selecione o Fiscal do Consórcio;
Selecione o Eng. Resp. Medições;
Selecione o Eng. Obras Construtora;
Situação da Obra;
Situação Atual do Contrato;
Observações Relatório Mensal;
Observações da Bacia;
Parceria/Realização;
Observações Gerais;
Observações para Apoio Gerencial.

**Comment by filipecoelho** [comment]
Lisiane, dos 372 empreendimentos cadastrados no sistema:
- 252 estão amarrados com algum contrato
- Dos 122 que não estão amarrados com nenhum contrato
  - 6 estão sem nenhuma situação (Situação de Obra e de Contrato)
  - 116 estão com situação ATENDIMENTO POTENCIAL (Situação de Obra e de Contrato)

Qual será o próximo passo:
- Criar os campos citados acima na tabela de dados do contrato e migrar estes dados para lá, mas é importante lembrar que serão migrados apenas os dados dos que houver contrato amarrado. Ou imagina que tenha outra saída?

**Comment by filipecoelho** [comment]
Acordado com Lisiane, que será analisado a situação de Guatapará - Sede I e Caconde - Sede e criação de campo de observações para Aguaí - ETE Itupeva - 40% da população

**Comment by lisianelaier** [comment]
Guatapará - Sede I -> Já deletei no sistema, pois não existe.
Temos outras situações semelhantes a Caconde. Para solucionar este problema, vamos criar um campo "Nome do contrato".

**Comment by filipecoelho** [comment]
Renomeação de campos na estrutura do banco de dados:
qtd_populacao_urbana_2010 			=		qtd_populacao_urbana_2010
Valor do Contrato 					=		vlr_investimento_governo
dta_inicio_obras 					=		dta_inicio_obras
num_percentual_executado 			=		num_percentual_executado
dta_previsao_termino 				=		dta_previsao_termino
dta_inauguracao 					=		dta_conclusao_inauguracao
dta_previsao_inauguracao 			=		dta_previsao_inauguracao
cod_fiscal 							=		cod_engenheiro_obras_consorcio
cod_engenheiro_daee 				=		cod_engenheiro_daee
cod_engenheiro_plan_consorcio 		=		cod_engenheiro_planejamento_obras_consorcio
cod_fiscal_consorcio 				=		cod_fiscal_consorcio
cod_engenheiro_medicao 				=		cod_engenheiro_responsavel_medicao
cod_engenheiro_construtora 			=		cod_engenheiro_obras_construtora
cod_situacao 						=		cod_situacao_obra
cod_situacao_externa 				=		cod_situacao_contrato
dsc_observacoes_relatorio_mensal	=		dsc_observacoes_relatorio_mensal
dsc_observacoes_obra 				=		dsc_observacoes_bacia
cod_parceiro 						=		cod_parceiro
dsc_parceria_realizacao 			=		dsc_parceria_realizacao
dsc_observacoes_gestor 				=		dsc_observacoes_gerais
dsc_observacoes_planejamento 		=		dsc_observacoes_apoio_gerencial

**Comment by filipecoelho** [comment]
Renomeação de campos na estrutura do banco de dados:
qtd_populacao_urbana_2010 = qtd_populacao_urbana_2010
Valor do Contrato = vlr_investimento_governo
dta_inicio_obras = dta_inicio_obras
num_percentual_executado = num_percentual_executado
dta_previsao_termino = dta_previsao_termino
dta_inauguracao = dta_conclusao_inauguracao
dta_previsao_inauguracao = dta_previsao_inauguracao
cod_fiscal = cod_engenheiro_obras_consorcio
cod_engenheiro_daee = cod_engenheiro_daee
cod_engenheiro_plan_consorcio = cod_engenheiro_planejamento_obras_consorcio
cod_fiscal_consorcio = cod_fiscal_consorcio
cod_engenheiro_medicao = cod_engenheiro_responsavel_medicao
cod_engenheiro_construtora = cod_engenheiro_obras_construtora
cod_situacao = cod_situacao_obra
cod_situacao_externa = cod_situacao_contrato
dsc_observacoes_relatorio_mensal = dsc_observacoes_relatorio_mensal
dsc_observacoes_obra = dsc_observacoes_bacia
cod_parceiro = cod_parceiro
dsc_parceria_realizacao = dsc_parceria_realizacao
dsc_observacoes_gestor = dsc_observacoes_gerais
dsc_observacoes_planejamento = dsc_observacoes_apoio_gerencial

**Comment by filipecoelho** [comment]
*vlr_investimento_governo
*dta_inicio_obras
*num_percentual_executado
*dta_previsao_termino
*dta_conclusao_inauguracao
*dta_previsao_inauguracao
*cod_engenheiro_obras_consorcio
*cod_engenheiro_daee
*cod_engenheiro_planejamento_obras_consorcio
*cod_fiscal_consorcio
*cod_engenheiro_responsavel_medicao
*cod_engenheiro_obras_construtora
*cod_situacao_obra
*cod_situacao_contrato
*dsc_observacoes_relatorio_mensal
*dsc_observacoes_bacia
*cod_parceiro
*dsc_parceria_realizacao
*dsc_observacoes_gerais
*dsc_observacoes_apoio_gerencial

**Comment by filipecoelho** [comment]
Procedimento p/ implantação:
- Criar campos citados acima na tabela tb_contrato
- Atualizar as consultas:
  - c_lista_contrato
  - c_lista_dados_obras
  - c_lista_rel_planilhao
  - c_lista_rel_info_complementares
  - c_lista_rel_contrato
- Atualizar as páginas:
  - cadastro_pi.asp
  - altera_pi.asp
  - ficha-tecnica-obra.asp
  - rel_planilhao.asp
  - rel_info_complementares.asp
  - resumo-situacao.asp
  - rel_contrato.asp
  - cad_contrato.asp
  - altera_contrato.asp

**Comment by filipecoelho** [comment]
@lisianelaier, favor homologar a migração de dados.
