### ISSUE TITLE
Ficha do Superintendente

### ISSUE THREAD

**Issue by lisianelaier** [filipecoelho/sig-intermultiplas#249]
Na ficha do Superintendente:
Em Info do contrato: (no final)
Acrescentar 2 campos:
% Executado: (info do empreendimento)
Vazão do sistema: (este campo ainda não existe, pode ser colocado junto com as informações complementares, em info do empreendimento).

**Comment by filipecoelho** [comment]
Lisiane, o campo [Vazão do Sistema] vai armazenar que tipo de informação?

**Comment by lisianelaier** [comment]
Nº  de 4 dígitos.
Colocar no nome do campo:  Vasão do sistema (l/s).

**Comment by lisianelaier** [comment]
Filipe,
O Sampaio pediu para vc. colocar o campo vazão do sistema em info da obra.
Entre  os campos "População Urbana (2010)" e "Objeto da Obra".
