### ISSUE TITLE
Campo "Observações Gerais"

### ISSUE THREAD

**Issue by lisianelaier** [filipecoelho/sig-intermultiplas#255]
Renomear o campo "Observações Gerais" em Atualização de Dados de Empreendimentos para "Observações para Apoio Gerencial".

**Comment by filipecoelho** [comment]
Lisiane, o campo mencionado já existe com esta nomenclatura.
Há diversos campos de observação no cadastro do empreendimento.
Acredito que seja interessante montar uma planilha com o nome do campo e respectivamente para que se destina cada um para evitar confusão.
