### ISSUE TITLE
colocar buscas na ordem estabelecida pelo Lupércio

### ISSUE THREAD

**Issue by rgualdanineto** [filipecoelho/sig-intermultiplas#34]
implementar até o Lupércio voltar:

Primeiro por Municípios (veja que município está escrito errado)
depois por universo de atendimento
depois por universo do programa e por último filtro por situação

![image](https://cloud.githubusercontent.com/assets/11915509/7127978/6cb31026-e222-11e4-9178-151ff81b55ca.png)

**Comment by filipecoelho** [comment]
Passos para implantação:
- Substituir/Fazer Upload do arquivo: atendimento-prefeito.asp
