### ISSUE TITLE
Relatórios administrador

### ISSUE THREAD

**Issue by rgualdanineto** [filipecoelho/sig-intermultiplas#45]
O administrador deve visualizar todos os relatórios e vamos discutir alguns outros baseados na tela antiga.
![image](https://cloud.githubusercontent.com/assets/11915509/7178957/a1a6e65c-e409-11e4-8a3b-c510ca3698c3.png)

**Comment by filipecoelho** [comment]
Passos para implantação:
- Substituir/Fazer upload do arquivo: login_adm.asp
