### ISSUE TITLE
tela relatório últimas ocorrências "no sistema"

### ISSUE THREAD

**Issue by rgualdanineto** [filipecoelho/sig-intermultiplas#46]
Na tela, no campo data (ao lado de responsável) colocar um link para a tela onde foi feito o registro. Para que possam ser feitas manutenções de registros pelas pessoas autorizadas.
![image](https://cloud.githubusercontent.com/assets/11915509/7179105/e87bddac-e40a-11e4-9e94-f33baf7d494a.png)

**Comment by filipecoelho** [comment]
Passos p/ implantação:
- Incluir campo cod_acompanhamento na consulta c_lista_rel_ultimas_ocorrencias
- Substituir/Fazer upload do arquivo: rel_ultimas_ocorr.asp
