### ISSUE TITLE
corrigir no relatório de ocorrências

### ISSUE THREAD

**Issue by rgualdanineto** [filipecoelho/sig-intermultiplas#48]
corrigir no banco:
![image](https://cloud.githubusercontent.com/assets/11915509/7179200/c2da51e0-e40b-11e4-8b8c-5254fd3df8a0.png)
e
![image](https://cloud.githubusercontent.com/assets/11915509/7179224/fdaf5090-e40b-11e4-8533-3577d772bae4.png)
existem outras ocorrências.

NOTAR QUE DEVEM SER MODIFICADAS NO BANCO E POSTERIORMENTE CONSIDERADAS NO BANCO PARA SUBIR NO SISTEMA. PARA NÃO PERDER A INFORMAÇÃO.

**Comment by filipecoelho** [comment]
Ao analisar o banco de dados não encontrei os registros com datas e horas.
Vou analisar com calma cada caso para ver se é regra de front-end

**Comment by filipecoelho** [comment]
Foi constatado o erro novamente no servidor programaagualimpa.net.
Estarei analisando amanhã

**Comment by filipecoelho** [comment]
Foi identificado em alguns registros o horário do lançamento, com isso não era possível agrupar as informações.
Para corrigir, deve-se atualizar o campo [Data do Registro] da tabela tb_Acompanhamento, nos casos onde é apresentado este horário
