### ISSUE TITLE
fotos do pmweb estão disponíveis

### ISSUE THREAD

**Issue by rgualdanineto** [filipecoelho/sig-intermultiplas#49]
Subir as fotos para produção.

**Comment by filipecoelho** [comment]
Passos para implantar:
- Importar planilha Sheet1 do arquivo DAEE.xlxs
- Criar consulta de inclusão com a seguinte query SQL:
INSERT INTO tb_acompanhamento_arquivo ( cod_referencia, nme_arquivo, pth_arquivo, dsc_observacoes )
SELECT tb_Acompanhamento.cod_acompanhamento AS cod_referencia, Sheet1.nme_arquivo, "e:\home\programaagualimpa\web\ARQUIVOS\ACOMPANHAMENTO\" AS pth_arquivo, Sheet1.Legenda AS dsc_observacoes
FROM tb_Acompanhamento INNER JOIN Sheet1 ON (Sheet1.autos = tb_Acompanhamento.PI) AND (tb_Acompanhamento.[Data do Registro] = Sheet1.[data pt_br]);
- Fazer upload dos arquivos para a pasta /ARQUIVOS/ACOMPANHAMENTO
