### ISSUE TITLE
"c_lista_rel_gestores"

### ISSUE THREAD

**Issue by lisianelaier** [filipecoelho/sig-intermultiplas#51]
Acrescentar no "c_lista_rel_gestores" a coluna eng_resp._med. (engenheiro responsável pelas medições -> Karla, Fábio, Cidinha)

**Comment by filipecoelho** [comment]
Passos para implementação:

- Replicar a consulta c_lista_rel_gestores corrigida do banco de desenvolvimento para o banco de produção
