### ISSUE TITLE
"c_lista_rel_contrato"

### ISSUE THREAD

**Issue by lisianelaier** [filipecoelho/sig-intermultiplas#52]
Acrescentar as colunas:
Data da O.S.;
Prazo total do contrato;
Prazo de execução total;
Data da conclusão da obra;
Contrapartida (não sei se ni sistema existe este campo, que é novo no planilhão...).

**Comment by filipecoelho** [comment]
Conforme conversado, os campos prazo total do contrato e prazo de execução total não devem estar no banco, portanto, não serão exibidos.

**Comment by filipecoelho** [comment]
Passos para implantação:
- Replicar a consulta c_lista_rel_contrato do banco de desenvolvimento para o banco de produção
