### ISSUE TITLE
"c_lista_rel_info_complementares"

### ISSUE THREAD

**Issue by lisianelaier** [filipecoelho/sig-intermultiplas#55]
Acrescentar coluna parceria cujo texto é:
"Secretaria de Saneamento e Recursos Hídricos
DAEE - Departamento de Águas e Energia Elétrica e Prefeitura Municipal"

**Comment by filipecoelho** [comment]
Passos para implantação:
- Replicar a consulta c_lista_rel_info_complementares do banco de desenvolvimento para o banco de produção
