### ISSUE TITLE
cadastro dos dados da licitação

### ISSUE THREAD

**Issue by lisianelaier** [filipecoelho/sig-intermultiplas#57]
Para completar esta fase de imput de dados no sistema, acho importante criar uma página para o cadastro dos dados da licitação, conforme “planilhão” colunas BD a BG:
- Nº do autos da licitação;
- Atendimento a município? (opções: Atendimento a Municípios; DAEE; PM)

**Comment by filipecoelho** [comment]
Será atendido pelo chamado #114
