### ISSUE TITLE
Campo população da localidade

### ISSUE THREAD

**Issue by lisianelaier** [filipecoelho/sig-intermultiplas#58]
Não estou conseguindo corrigir a população de uma localidade. Está dando o seguinte erro:
Microsoft JET Database Engine error '80040e14'
Syntax error in UPDATE statement.
/altera_pi.asp, line 286

**Comment by filipecoelho** [comment]
Não consegui reproduzir o erro.
Ao efetuar o login como Administrador e trocar para o perfil de Informações Gerenciais, foi feita a atualização de dados com sucesso!
