### ISSUE TITLE
Corrigir 3 datas que contém horários

### ISSUE THREAD

**Issue by claudineysiqueira** [filipecoelho/sig-intermultiplas#62]
Corrigir três datas de registro na tabela tb_Acompanhamento, pois as mesmas exibem o horário, sendo:
Acompanhamento nº:
3173 (07/03/2015);
3243 (02/09/2014), e
3244 (07/10/2014.
Ou seja, manter as datas existentes, e deletar apenas os horários contidos.

**Comment by filipecoelho** [comment]
Estarei analisando pelo #48
