### ISSUE TITLE
Verificar espaço para campo "registro" no RDO

### ISSUE THREAD

**Issue by danieldepaula** [filipecoelho/sig-intermultiplas#64]
Filipe, recebi um e-mail do pessoal de obra com relação ao espaço destinado ao registro das ocorrências.

"Boa tarde Daniel, 

Tenho uma dúvida referente ao novo sistema.
No campo "Registro" as informações que tenho para lançamento não cabe no espaço destinado, como devo proceder?

Att, 
João Vitor"

**Comment by filipecoelho** [comment]
Corrigido emergencialmente na sexta-feira
