### ISSUE TITLE
Valor do cotrato

### ISSUE THREAD

**Issue by lisianelaier** [filipecoelho/sig-intermultiplas#73]
Fazendo a verificação dos dados que subiram para o sistema encontrei um valor de contrato errado.
Onde devo ir para corrigir o valor original do contrato e o valor com aditivo?

**Comment by filipecoelho** [comment]
O campo valor do contrato é exibindo na alteração de cadastro de empreendimento no campo Valor Investido pelo Governo.
O campo valor com aditivo não existe no banco de dados, apenas um campo Valor do Aditamento, e este campo não tem como atualizar via sistema.
Se for o caso, envie para o Claudiney os registros que precisam ser atualizados e sobe tudo hoje a noite, com outras correções.

**Comment by lisianelaier** [comment]
Já passei a planilha revista para o Claudiney, porém este problema ainda vai continuar existindo, pois ainda estamos colhendo este tipo de informações...

**Comment by filipecoelho** [comment]
será tratado pelo chamado #81
