### ISSUE TITLE
Erro no sistema

### ISSUE THREAD

**Issue by lisianelaier** [filipecoelho/sig-intermultiplas#75]
Erro:
Ao tentar atualizar o % de avanço deu o seguinte erro:
Microsoft JET Database Engine error '80040e14'
Syntax error in UPDATE statement.
/altera_pi.asp, line 286

**Comment by filipecoelho** [comment]
Todas atualizações de empreendimento estão dando problema, vou precisar rever esta tela.

**Comment by filipecoelho** [comment]
referente ao chamado #58
