### ISSUE TITLE
Lembrete de pendência via e-mail.

### ISSUE THREAD

**Issue by rgualdanineto** [filipecoelho/sig-intermultiplas#79]
Filipe,
Favor implementar um lembrete por e-mail para o usuário abaixo, as pendências serão cadastradas com a data limite de pendência e nesta data deve ser disparado um e-mail com o texto da pendência para o e-mail: roberto.fortes@intermultiplas.com.br .
Genericamente poderíamos acrescentar um botão ao lado da pendência para efetuarmos este acompanhamento automaticamente. 

Rinaldo

Gostaria de receber a informação/lembrete sobre a "pendência" que eu mesmo coloquei/criei.
Desta forma o sistema poderá lembrar-me (caso esquecí) sobre o assunto.

grato
Roberto Rigo Fortes
Consórcio Inter Múltiplas
Rua Boa Vista, 170 - 8º Andar
Cep: 01.014-000 - São Paulo, SP
Tel.: (11) 3293-3118

**Comment by filipecoelho** [comment]
Conforme acordado, a princípio não haverá o sistema de envio de e-mail devido limitações técnicas da linguagem de programação utilizada no projeto (ASP).

**Comment by rgualdanineto** [comment]
Deixar claro aos usuários.  Principalmente o Roberto.
Em 30/04/2015 18:13, "Filipe Coelho" <notifications@github.com> escreveu:

**Comment by filipecoelho** [comment]
associada ao #154
