### ISSUE TITLE
perfil administrador solicite ficha técnica via menu de relatórios

### ISSUE THREAD

**Issue by rgualdanineto** [filipecoelho/sig-intermultiplas#88]

**Comment by rgualdanineto** [comment]
também não está funcionando por outras fromas de solicitação ex: superintendente

**Comment by rgualdanineto** [comment]
não aparece para OBRA FINALIZADA OPERANDO E NÃO INAUGURADA e em atendimento.

**Comment by filipecoelho** [comment]
Não foi possível replicar o erro.
